/* =========================================================
Nombre completo: repo.app.js
Ruta o ubicación: /Requisitos/Reportes/repo.app.js
Función o funciones:
- Renderizar el módulo Reportes.
- Manejar filtros por tipo, período, matrícula, carrera, tablas, vista previa, copiado, impresión y exportación.
- Mostrar activos por defecto.
Con qué se conecta:
- repo.core.js
- repo.export.js
========================================================= */
(function(window,document){
  "use strict";
  var state={tipo:"general",periodId:"",matricula:"ACTIVO",career:"",data:null};
  function el(id){return document.getElementById(id);}function text(v){return String(v==null?"":v).trim();}
  function esc(v){return text(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}
  function status(msg,cls){var s=el("repo-status");if(s){s.textContent=msg;s.className="repo-status "+(cls||"");}}
  function option(value,label,selected){return '<option value="'+esc(value)+'" '+(selected?'selected':'')+'>'+esc(label)+'</option>';}
  function fillFilters(data){var p=el("repo-periodo");var c=el("repo-carrera");var m=el("repo-matricula");if(p){p.innerHTML=option("","Todos",!state.periodId)+(data.periodList||[]).map(function(x){return option(x.id,x.label||x.id,state.periodId===x.id);}).join("");}if(m){m.value=state.matricula;}if(c){c.innerHTML=option("","Todas",!state.career)+(data.careerList||[]).map(function(x){return option(x,x,state.career===x);}).join("");}}
  function pill(kind,value){var cls=kind==="ok"?"pill-ok":kind==="bad"?"pill-bad":"pill-warn";return '<span class="pill '+cls+'">'+esc(value)+'</span>';}
  function table(headers,rows){if(!rows||!rows.length)return '<div class="empty">Sin datos.</div>';var html='<table><thead><tr>'+headers.map(function(h){return '<th>'+esc(h.label)+'</th>';}).join('')+'</tr></thead><tbody>';html+=rows.map(function(row){return '<tr>'+headers.map(function(h){var value=typeof h.value==="function"?h.value(row):row[h.key];return '<td>'+value+'</td>';}).join('')+'</tr>';}).join('');return html+'</tbody></table>';}
  function renderTables(data){el("repo-carreras").innerHTML=table([{label:"Carrera",key:"key"},{label:"Total",key:"total"},{label:"Cumple",value:function(r){return pill("ok",r.cumple);}},{label:"Pendiente",value:function(r){return pill("warn",r.pendiente);}},{label:"No cumple",value:function(r){return pill("bad",r.no_cumple);}},{label:"Avance",value:function(r){return r.avance+"%";}}],data.carreras);el("repo-carreras-meta").textContent=(data.carreras||[]).length+" carreras";el("repo-requisitos").innerHTML=table([{label:"Requisito",key:"label"},{label:"Cumple",value:function(r){return pill("ok",r.cumple);}},{label:"Pendiente",value:function(r){return pill("warn",r.pendiente);}},{label:"No cumple",value:function(r){return pill("bad",r.no_cumple);}},{label:"Atención",key:"atencion"}],data.requisitos);var pend=(data.pendientes||[]).slice(0,300);el("repo-estudiantes").innerHTML=table([{label:"Estudiante",value:function(r){return esc(r._nombres||"Sin nombre");}},{label:"Cédula",value:function(r){return '<span class="nowrap">'+esc(r._cedula)+'</span>'; }},{label:"Carrera",value:function(r){return esc(r._carrera);}},{label:"Matrícula",value:function(r){return pill(r._estadoMatricula==="RETIRADO"?"bad":"ok",r._estadoMatricula);}},{label:"Estado",value:function(r){return pill(r._estado.id==="no_cumple"?"bad":"warn",r._estado.label);}},{label:"Pend.",value:function(r){return r._estado.pend;}},{label:"No",value:function(r){return r._estado.no;}}],pend);el("repo-estudiantes-meta").textContent=(data.pendientes||[]).length+" estudiantes";}
  function render(){try{state.data=window.RepoCore.build({tipo:state.tipo,periodId:state.periodId,matricula:state.matricula,career:state.career});var d=state.data;fillFilters(d);el("repo-total").textContent=d.kpis.total;el("repo-ok").textContent=d.kpis.cumple;el("repo-pend").textContent=d.kpis.pendiente;el("repo-no").textContent=d.kpis.no_cumple;el("repo-avance").textContent=d.kpis.avance+"%";el("repo-preview").value=d.text;el("repo-generated-at").textContent=new Date(d.generatedAt).toLocaleString();renderTables(d);el("repo-diagnostics").textContent=JSON.stringify({generatedAt:d.generatedAt,filters:d.filters,total:d.kpis.total,carreras:d.carreras.length,requisitos:d.requisitos.length,pendientes:d.pendientes.length},null,2);status("Reportes cargado correctamente. Matrícula: "+(state.matricula||"Todos")+".","ok");}catch(e){console.error("[Reportes]",e);status(e.message||String(e),"warn");}}
  function bind(){el("repo-tipo").addEventListener("change",function(e){state.tipo=e.target.value;render();});el("repo-periodo").addEventListener("change",function(e){state.periodId=e.target.value;render();});el("repo-matricula").addEventListener("change",function(e){state.matricula=e.target.value;state.career="";render();});el("repo-carrera").addEventListener("change",function(e){state.career=e.target.value;render();});el("repo-refresh").addEventListener("click",render);el("repo-copy").addEventListener("click",function(){window.RepoExport.copyText(state.data&&state.data.text).then(function(){status("Reporte copiado.","ok");});});el("repo-print").addEventListener("click",function(){window.print();});el("repo-export-txt").addEventListener("click",function(){window.RepoExport.exportTxt(state.data);});el("repo-export-html").addEventListener("click",function(){window.RepoExport.exportHtml(state.data);});el("repo-export-json").addEventListener("click",function(){window.RepoExport.exportJson(state.data);});}
  function boot(){if(window.ExcelLocalBridge)window.ExcelLocalBridge.ensureReady();bind();render();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})(window,document);
