/* =========================================================
Nombre completo: defart.core.js
Ruta o ubicación: /Requisitos/defart/defart.core.js
Función o funciones:
- Leer estudiantes activos desde BaseLocal/ExcelLocalRepo.
- Normalizar campos reales de Firebase para Defensas.
- Filtrar por período, división, carrera, estado, sede y búsqueda.
- Habilitar N-ART según requisitos cumplidos/aprobados.
- Habilitar N-DEF solo si N-ART es igual o mayor a 7.
- Guardar Notart, Notdef y Notafinal en BaseLocal.
Con qué se conecta:
- excel-local.repo.js
- excel-local.storage.js
- baselocal.connector.js
- bl-periodos-canon.service.js
- bl-divisiones.service.js
- defart.app.js
========================================================= */
(function(window){
  "use strict";
  var PASS_VALUES=["cumple","aprobado"];
  var STATES=["Sin requisitos","Pendiente Art","Supletorio Art","Pendiente Def","Supletorio Def","Completo"];
  var REQUIREMENTS=[
    {key:"academico",label:"Académico",fields:["Academico","Académico","academico"]},
    {key:"documentacion",label:"Documentación",fields:["Documentacion","Documentación","documentacion"]},
    {key:"financiero",label:"Financiero",fields:["Financiero","financiero"]},
    {key:"titulacion",label:"Titulación",fields:["Titulacion","Titulación","titulacion"]},
    {key:"vinculacion",label:"Vinculación",fields:["Vinculacion","Vinculación","vinculacion"]},
    {key:"seguimiento",label:"Seguimiento graduados",fields:["SeguimientoGraduados","Seguimiento graduados","SeguimientoGraduado","seguimientoGraduados"]},
    {key:"ingles",label:"Inglés",fields:["Ingles","Inglés","ingles"]},
    {key:"actualizacion",label:"Actualización datos",fields:["ActualizaciónDatos","ActualizacionDatos","Actualización datos","actualizacionDatos","actualizaciondatos"]}
  ];
  function text(value){return String(value==null?"":value).trim();}
  function now(){return new Date().toISOString();}
  function norm(value){return text(value).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim().toLowerCase();}
  function clone(value){try{return JSON.parse(JSON.stringify(value==null?null:value));}catch(error){return value;}}
  function repo(){if(!window.ExcelLocalRepo){throw new Error("ExcelLocalRepo no disponible. Primero abre BL o Carga para inicializar BaseLocal.");}return window.ExcelLocalRepo;}
  function storage(){return window.ExcelLocalStorage&&typeof window.ExcelLocalStorage.readSnapshot==="function"?window.ExcelLocalStorage:null;}
  function getSnapshot(){if(storage())return storage().readSnapshot();if(repo().getSnapshot)return repo().getSnapshot();return {periods:[],students:[],history:[],meta:{}};}
  function writeSnapshot(snapshot){var saved=storage()&&typeof storage().writeSnapshot==="function"?storage().writeSnapshot(snapshot):snapshot;try{if(window.RequisitosBL&&typeof window.RequisitosBL.rebuildSnapshotToCollections==="function"){window.RequisitosBL.rebuildSnapshotToCollections({force:true,silent:true});window.RequisitosBL.notificar("snapshot-changed",{source:"defart.core",updatedAt:now()});}else if(window.RequisitosBL&&typeof window.RequisitosBL.mirrorSnapshotToCollections==="function"){window.RequisitosBL.mirrorSnapshotToCollections({force:true,silent:true});window.RequisitosBL.notificar("snapshot-changed",{source:"defart.core",updatedAt:now()});}}catch(error){}return saved;}
  function backupSnapshot(snapshot,reason){try{window.localStorage.setItem("REQ_DEFART_BACKUP_V1:"+Date.now(),JSON.stringify({reason:reason||"before_save",createdAt:now(),snapshot:clone(snapshot)}));}catch(error){}}
  function rawStudents(){return repo().listAllStudents?repo().listAllStudents():(getSnapshot().students||[]);}
  function rawPeriods(){return repo().listPeriods?repo().listPeriods():(getSnapshot().periods||[]);}
  function pick(row,names){row=row||{};for(var i=0;i<names.length;i+=1){if(text(row[names[i]])!=="")return row[names[i]];}return "";}
  function noteString(value){return text(value).replace(",",".");}
  function numberValue(value){if(value===null||value===undefined||text(value)==="")return null;var num=Number(noteString(value));return Number.isFinite(num)?num:null;}
  function round2(value){return Number.isFinite(value)?Math.round(value*100)/100:null;}
  function noteToText(value){var num=numberValue(value);return num===null?"":String(round2(num));}
  function hasMaxTwoDecimals(value){var raw=noteString(value);if(!raw)return true;return /^\d{1,2}(\.\d{0,2})?$|^10(\.0{0,2})?$|^0(\.\d{0,2})?$/.test(raw);}
  function isValidNote(value){if(text(value)==="")return true;var num=numberValue(value);return num!==null&&num>=0&&num<=10&&hasMaxTwoDecimals(value);}
  function requirementValue(row,req){return text(pick(row,req.fields));}
  function requirementOk(value){return PASS_VALUES.indexOf(norm(value))>=0;}
  function requirementSummary(row){var missing=[],values={};REQUIREMENTS.forEach(function(req){var value=requirementValue(row,req);values[req.key]=value;if(!requirementOk(value))missing.push(req.label);});return {ok:missing.length===0,missing:missing,values:values};}
  function isActive(row){var value=norm(pick(row,["estadoMatricula","EstadoMatricula","estado","Estado"]));if(!value)return true;return value==="activo";}
  function studentId(row,index){return text(pick(row,["_docId","docId","cedula","Cedula","CEDULA","numeroIdentificacion","numeroidentificacion","NumeroIdentificacion","identificacion","Identificacion"]))||("fila_"+index);}
  function periodId(row){return text(pick(row,["periodoId","ultimoPeriodoId","periodId","PeriodoId","periodo","Periodo"]));}
  function periodLabel(row){return text(pick(row,["periodoLabel","PeriodoLabel","periodo","Periodo"]))||periodId(row)||"Sin período";}
  function samePeriod(a,b){if(!text(b))return true;if(window.BLPeriodosCanon&&typeof window.BLPeriodosCanon.samePeriod==="function")return window.BLPeriodosCanon.samePeriod(a,b);return text(a)===text(b);}
  function divisionOf(row){if(window.BLDivisionesService&&typeof window.BLDivisionesService.studentDivision==="function")return window.BLDivisionesService.studentDivision(row);var list=Array.isArray(row&&row.divisiones)?row.divisiones:[];return list[0]||row.division||"Sin división";}
  function hasDivision(row,division){if(!text(division))return true;if(window.BLDivisionesService&&typeof window.BLDivisionesService.hasDivision==="function")return window.BLDivisionesService.hasDivision(row,division);return norm(divisionOf(row))===norm(division);}
  function calculateFinal(nart,ndef){if(nart===null||ndef===null)return null;if(nart<7)return null;return round2((nart*.70)+(ndef*.30));}
  function decorate(row,index){var source=Object.assign({},row||{});var req=requirementSummary(source);var nart=numberValue(pick(source,["Notart","Nart","N_ART","N-ART","notart","notaArticulo","nota_articulo"]));var ndef=numberValue(pick(source,["Notdef","Ndef","N_DEF","N-DEF","notdef","notaDefensa","nota_defensa"]));var canArt=req.ok;var canDef=canArt&&nart!==null&&nart>=7;var nfin=canDef?calculateFinal(nart,ndef):null;var estado="Pendiente Art";if(!canArt)estado="Sin requisitos";else if(nart===null)estado="Pendiente Art";else if(nart<7)estado="Supletorio Art";else if(ndef===null)estado="Pendiente Def";else if(ndef<7)estado="Supletorio Def";else estado="Completo";source._defId=studentId(source,index);source._cedula=text(pick(source,["cedula","Cedula","CEDULA","numeroIdentificacion","numeroidentificacion","NumeroIdentificacion","identificacion","Identificacion"]));source._nombre=text(pick(source,["Nombres","nombres","Nombre","nombre","estudiante","Estudiante","apellidosNombres","apellidos_nombres"]));source._carrera=text(pick(source,["NombreCarrera","nombrecarrera","nombreCarrera","Carrera","carrera","programa","Programa"]))||"SIN CARRERA";source._division=divisionOf(source);source._sede=text(pick(source,["Sede","sede","campus"]))||"SIN SEDE";source._periodoId=periodId(source);source._periodoLabel=periodLabel(source);source._estadoMatricula=text(pick(source,["estadoMatricula","EstadoMatricula","estado","Estado"]))||"ACTIVO";source._nart=nart;source._ndef=ndef;source._nfin=nfin;source._canArt=canArt;source._canDef=canDef;source._estadoDefensa=estado;source._missingRequirements=req.missing;source._requirementValues=req.values;return source;}
  function preview(row,patch){var next=Object.assign({},row||{});patch=patch||{};if(Object.prototype.hasOwnProperty.call(patch,"nart"))next.Notart=numberValue(patch.nart);if(Object.prototype.hasOwnProperty.call(patch,"ndef"))next.Notdef=numberValue(patch.ndef);return decorate(next,0);}
  function unique(list,getter){var map={};(list||[]).forEach(function(item){var value=text(getter(item));if(value)map[value]=true;});return Object.keys(map).sort(function(a,b){return a.localeCompare(b,"es");});}
  function periodOptions(rows){var map={};rawPeriods().forEach(function(period){var p=window.BLPeriodosCanon&&typeof window.BLPeriodosCanon.normalizePeriod==="function"?window.BLPeriodosCanon.normalizePeriod(period):period;var id=text(p.id||p.periodoId||p.value);if(id)map[id]={id:id,label:text(p.label||p.periodoLabel||id)};});rows.forEach(function(row){if(row._periodoId&&!map[row._periodoId])map[row._periodoId]={id:row._periodoId,label:row._periodoLabel||row._periodoId};});return Object.keys(map).map(function(key){return map[key];}).sort(function(a,b){return String(a.label||a.id).localeCompare(String(b.label||b.id),"es");});}
  function compareValues(a,b,key){var av=a[key],bv=b[key];if(key==="_nart"||key==="_ndef"||key==="_nfin"){av=av===null?-1:av;bv=bv===null?-1:bv;return av-bv;}return String(av==null?"":av).localeCompare(String(bv==null?"":bv),"es",{numeric:true,sensitivity:"base"});}
  function filterRows(options){options=options||{};var q=norm(options.search||"");var rows=rawStudents().filter(isActive).map(decorate).filter(function(row){if(options.periodId&&!samePeriod(row._periodoId,options.periodId))return false;if(options.division&&!hasDivision(row,options.division))return false;if(options.career&&row._carrera!==options.career)return false;if(options.status&&row._estadoDefensa!==options.status)return false;if(options.sede&&row._sede!==options.sede)return false;if(q){var hay=norm([row._cedula,row._nombre,row._carrera,row._division,row._sede,row._periodoLabel,row._estadoDefensa].join(" "));if(hay.indexOf(q)<0)return false;}return true;});if(options.sortKey){rows.sort(function(a,b){var result=compareValues(a,b,options.sortKey);return options.sortDir==="desc"?-result:result;});}else rows.sort(function(a,b){return a._nombre.localeCompare(b._nombre,"es");});return rows;}
  function kpis(rows){var result={total:rows.length};STATES.forEach(function(state){result[state]=0;});rows.forEach(function(row){if(Object.prototype.hasOwnProperty.call(result,row._estadoDefensa))result[row._estadoDefensa]+=1;});return result;}
  function diagnosticsFromRows(allActive,rows,options){var notes={withNart:0,withNdef:0,withNfin:0};allActive.forEach(function(row){if(row._nart!==null)notes.withNart+=1;if(row._ndef!==null)notes.withNdef+=1;if(row._nfin!==null)notes.withNfin+=1;});var connectorCounts=null;try{if(window.RequisitosBL&&typeof window.RequisitosBL.conteos==="function")connectorCounts=window.RequisitosBL.conteos();}catch(error){}return {ok:true,generatedAt:now(),version:"defensas-divisiones",source:"BaseLocal",totalActive:allActive.length,visible:rows.length,notes:notes,filters:options||{},connections:{excelLocalRepo:!!window.ExcelLocalRepo,excelLocalStorage:!!window.ExcelLocalStorage,requisitosBL:!!window.RequisitosBL,baseLocalBridge:!!window.BaseLocalBridge,exportExcel:!!window.DefartExport,blCounts:connectorCounts}};}
  function summary(options){options=options||{};var allActive=rawStudents().filter(isActive).map(decorate);var rows=filterRows(options);var baseForDivision=allActive.filter(function(row){return !options.periodId||samePeriod(row._periodoId,options.periodId);});var baseForCareer=baseForDivision.filter(function(row){return !options.division||hasDivision(row,options.division);});return {rows:rows,kpis:kpis(rows),periodList:periodOptions(allActive),divisionList:(window.BLDivisionesService&&window.BLDivisionesService.listDivisionsWithEmpty)?window.BLDivisionesService.listDivisionsWithEmpty(baseForDivision,""):unique(baseForDivision,function(row){return row._division;}),careerList:unique(baseForCareer,function(row){return row._carrera;}),sedeList:unique(rows.length?rows:baseForCareer,function(row){return row._sede;}),states:STATES.slice(),diagnostics:diagnosticsFromRows(allActive,rows,options)};}
  function findStudentIndex(students,id){id=text(id);for(var i=0;i<students.length;i+=1){if(studentId(students[i],i)===id)return i;}return -1;}
  function normalizePatch(patch){var out={};if(Object.prototype.hasOwnProperty.call(patch,"nart"))out.Notart=numberValue(patch.nart);if(Object.prototype.hasOwnProperty.call(patch,"ndef"))out.Notdef=numberValue(patch.ndef);return out;}
  function validateChange(current,change,patch,nart,ndef){var errors=[];if(Object.prototype.hasOwnProperty.call(change,"nart")&&!isValidNote(change.nart))errors.push("N-ART inválida: "+current._nombre);if(Object.prototype.hasOwnProperty.call(change,"ndef")&&!isValidNote(change.ndef))errors.push("N-DEF inválida: "+current._nombre);if(Object.prototype.hasOwnProperty.call(change,"nart")&&!current._canArt)errors.push("N-ART bloqueada por requisitos: "+current._nombre);if(Object.prototype.hasOwnProperty.call(change,"ndef")&&(!current._canArt||nart===null||nart<7))errors.push("N-DEF bloqueada hasta que N-ART sea 7 o más: "+current._nombre);if(nart!==null&&(nart<0||nart>10))errors.push("N-ART fuera de rango: "+current._nombre);if(ndef!==null&&(ndef<0||ndef>10))errors.push("N-DEF fuera de rango: "+current._nombre);return errors;}
  function saveNotes(changes){changes=Array.isArray(changes)?changes:[];if(!changes.length)return {ok:true,saved:0,total:0,message:"No hay cambios pendientes."};var snapshot=getSnapshot();snapshot.students=Array.isArray(snapshot.students)?snapshot.students:[];snapshot.history=Array.isArray(snapshot.history)?snapshot.history:[];backupSnapshot(snapshot,"before_defensas_save");var saved=0,errors=[],savedPeriodMap={};changes.forEach(function(change){var index=findStudentIndex(snapshot.students,change.id);if(index<0){errors.push("No encontrado: "+change.id);return;}var current=decorate(snapshot.students[index],index);var patch=normalizePatch(change);var nart=Object.prototype.hasOwnProperty.call(patch,"Notart")?patch.Notart:current._nart;var ndef=Object.prototype.hasOwnProperty.call(patch,"Notdef")?patch.Notdef:current._ndef;var validationErrors=validateChange(current,change,patch,nart,ndef);if(validationErrors.length){errors=errors.concat(validationErrors);return;}patch.Notafinal=calculateFinal(nart,ndef);patch.ultimaEdicionLocal=now();patch.updatedAt=now();snapshot.students[index]=Object.assign({},snapshot.students[index],patch);if(current._periodoId)savedPeriodMap[current._periodoId]=true;saved+=1;});if(saved>0){var periodIds=Object.keys(savedPeriodMap);snapshot.meta=Object.assign({},snapshot.meta||{},{updatedAt:now(),lastDefensasUpdateAt:now(),lastDefensasSaved:saved,lastDefensasPeriodos:periodIds});snapshot.history.unshift({id:"defensas_notas_"+Date.now(),action:"guardarNotasDefensas",periodoId:periodIds.length===1?periodIds[0]:"VARIOS",periodoLabel:periodIds.length===1?periodIds[0]:"Varios",fileName:"Defensas",totalRows:saved,errores:errors.length,createdAt:now()});writeSnapshot(snapshot);}return {ok:errors.length===0,saved:saved,total:changes.length,errors:errors,message:saved+" cambio(s) guardado(s) en BaseLocal."};}
  function selfTest(){var result={ok:true,checkedAt:now(),version:"defensas-divisiones",checks:[]};function check(name,ok,detail){result.checks.push({name:name,ok:!!ok,detail:detail||""});if(!ok)result.ok=false;}var snap=null;try{snap=getSnapshot();check("BaseLocal snapshot",true,"Snapshot leído");}catch(error){check("BaseLocal snapshot",false,error.message||String(error));}check("ExcelLocalRepo",!!window.ExcelLocalRepo,"Repositorio local");check("ExcelLocalStorage",!!window.ExcelLocalStorage,"Storage local");check("RequisitosBL",!!window.RequisitosBL,"Conector BL");check("BLDivisionesService",!!window.BLDivisionesService,"Divisiones");check("DefartExport",!!window.DefartExport,"Exportación Excel");if(snap){check("Estudiantes",Array.isArray(snap.students),(snap.students||[]).length+" registros");check("Períodos",Array.isArray(snap.periods),(snap.periods||[]).length+" períodos");}result.message=result.ok?"Diagnóstico correcto.":"Hay puntos por revisar.";return result;}
  window.DefartCore={summary:summary,saveNotes:saveNotes,decorate:decorate,preview:preview,noteToText:noteToText,isValidNote:isValidNote,calculateFinal:calculateFinal,selfTest:selfTest,requirements:REQUIREMENTS.slice(),states:STATES.slice(),divisionOf:divisionOf};
})(window);
