/* =========================================================
Nombre completo: defart.app.js
Ruta o ubicación: /Requisitos/defart/defart.app.js
Función o funciones:
- Renderizar panel de defensas.
- Manejar filtros, selección, mensajes y exportación.
Con qué se conecta:
- defart.core.js
- defart.export.js
========================================================= */
(function(window,document){
  "use strict";
  var state={periodId:"",career:"",sede:"",modo:"",search:"",messageType:"individual",selectedId:"",data:null};
  function el(id){return document.getElementById(id);}function text(v){return String(v==null?"":v).trim();}
  function esc(v){return text(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}
  function status(msg,cls){var s=el("def-status");if(s){s.textContent=msg;s.className="def-status "+(cls||"");}}
  function option(value,label,selected){return '<option value="'+esc(value)+'" '+(selected?'selected':'')+'>'+esc(label)+'</option>';}
  function fillFilters(data){var p=el("def-periodo"),c=el("def-carrera"),s=el("def-sede");if(p)p.innerHTML=option("","Todos",!state.periodId)+(data.periodList||[]).map(function(x){return option(x.id,x.label||x.id,state.periodId===x.id);}).join("");if(c)c.innerHTML=option("","Todas",!state.career)+(data.careerList||[]).map(function(x){return option(x,x,state.career===x);}).join("");if(s)s.innerHTML=option("","Todas",!state.sede)+(data.sedeList||[]).map(function(x){return option(x,x,state.sede===x);}).join("");}
  function pill(kind,value){var cls=kind==="ok"?"pill-ok":kind==="bad"?"pill-bad":kind==="blue"?"pill-blue":"pill-warn";return '<span class="pill '+cls+'">'+esc(value)+'</span>';}
  function table(headers,rows,opts){if(!rows||!rows.length)return '<div class="empty">Sin datos.</div>';opts=opts||{};var html='<table><thead><tr>'+headers.map(function(h){return '<th>'+esc(h.label)+'</th>';}).join('')+'</tr></thead><tbody>';html+=rows.map(function(row){var cls=opts.rowClass?opts.rowClass(row):'';var id=opts.rowId?opts.rowId(row):'';return '<tr class="'+esc(cls)+'" data-row-id="'+esc(id)+'">'+headers.map(function(h){var value=typeof h.value==="function"?h.value(row):row[h.key];return '<td>'+value+'</td>';}).join('')+'</tr>';}).join('');return html+'</tbody></table>';}
  function selected(){var rows=(state.data&&state.data.rows)||[];return rows.find(function(r){return r._id===state.selectedId;})||rows[0]||null;}
  function renderAgenda(data){var rows=(data.rows||[]).slice(0,500);el("def-agenda").innerHTML=table([{label:"Estado",value:function(r){return r._programada?pill("ok","Programada"):pill("warn","Sin fecha");}},{label:"Fecha",value:function(r){return esc(r._fecha||"—");}},{label:"Hora",value:function(r){return esc(r._hora||"—");}},{label:"Estudiante",value:function(r){return esc(r._nombres||"Sin nombre");}},{label:"Cédula",value:function(r){return '<span class="nowrap">'+esc(r._cedula)+'</span>'; }},{label:"Carrera",value:function(r){return esc(r._carrera);}},{label:"Sede/Modo",value:function(r){return esc([r._sede,r._modo].filter(Boolean).join(" / ")||"—");}},{label:"Aula",value:function(r){return esc(r._aula||"—");}},{label:"Tribunal",value:function(r){return esc([r._tribunal1,r._tribunal2].filter(Boolean).join(" / ")||"—");}}],rows,{rowId:function(r){return r._id;},rowClass:function(r){return r._id===state.selectedId?"is-selected":"";}});el("def-agenda-meta").textContent=(data.rows||[]).length+" registros";el("def-agenda").querySelectorAll("[data-row-id]").forEach(function(tr){tr.addEventListener("click",function(){state.selectedId=tr.getAttribute("data-row-id");renderMessage();renderAgenda(state.data);});});}
  function renderTables(data){el("def-carreras").innerHTML=table([{label:"Carrera",key:"key"},{label:"Total",key:"total"},{label:"Programadas",value:function(r){return pill("ok",r.programadas);}},{label:"Sin fecha",value:function(r){return pill("warn",r.sinFecha);}},{label:"Virtuales",key:"virtuales"},{label:"Presenciales",key:"presenciales"}],data.carreras);el("def-carreras-meta").textContent=(data.carreras||[]).length+" carreras";el("def-tribunales").innerHTML=table([{label:"Tribunal / Aula",key:"key"},{label:"Total",key:"total"}],data.tribunales);}
  function renderMessage(){var msg=window.DefartCore.message(state.data,state.messageType,selected());el("def-message").value=msg;}
  function render(){try{state.data=window.DefartCore.summary({periodId:state.periodId,career:state.career,sede:state.sede,modo:state.modo,search:state.search});var d=state.data;if(!d.rows.some(function(r){return r._id===state.selectedId;}))state.selectedId=d.rows[0]?d.rows[0]._id:"";fillFilters(d);el("def-total").textContent=d.kpis.total;el("def-programadas").textContent=d.kpis.programadas;el("def-sin-fecha").textContent=d.kpis.sinFecha;el("def-virtuales").textContent=d.kpis.virtuales;el("def-presenciales").textContent=d.kpis.presenciales;renderAgenda(d);renderTables(d);renderMessage();el("def-diagnostics").textContent=JSON.stringify(d.diagnostics,null,2);status("Defensas cargado correctamente.","ok");}catch(e){console.error("[Defensas]",e);status(e.message||String(e),"warn");}}
  function bind(){el("def-periodo").addEventListener("change",function(e){state.periodId=e.target.value;render();});el("def-carrera").addEventListener("change",function(e){state.career=e.target.value;render();});el("def-sede").addEventListener("change",function(e){state.sede=e.target.value;render();});el("def-modo").addEventListener("change",function(e){state.modo=e.target.value;render();});el("def-search").addEventListener("input",function(e){state.search=e.target.value;render();});el("def-message-type").addEventListener("change",function(e){state.messageType=e.target.value;renderMessage();});el("def-refresh").addEventListener("click",render);el("def-copy-message").addEventListener("click",function(){window.DefartExport.copyText(el("def-message").value).then(function(){status("Mensaje copiado.","ok");});});el("def-export-csv").addEventListener("click",function(){window.DefartExport.exportCsv(state.data&&state.data.rows);});el("def-export-json").addEventListener("click",function(){window.DefartExport.exportJson(state.data);});el("def-export-ics").addEventListener("click",function(){window.DefartExport.exportIcs(state.data&&state.data.rows);});}
  function boot(){if(window.ExcelLocalBridge)window.ExcelLocalBridge.ensureReady();bind();render();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})(window,document);
