/* =========================================================
Nombre completo: defart.core.js
Ruta o ubicación: /Requisitos/defart/defart.core.js
Función o funciones:
- Leer estudiantes desde BaseLocal/ExcelLocalRepo.
- Normalizar campos de defensa: fecha, hora, aula, sede, modo y tribunal.
- Generar agenda, resúmenes y mensajes de notificación.
Con qué se conecta:
- excel-local.repo.js
- defart.app.js
========================================================= */
(function(window){
  "use strict";
  function text(v){return String(v==null?"":v).trim();}
  function norm(v){return text(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();}
  function repo(){if(!window.ExcelLocalRepo)throw new Error("ExcelLocalRepo no disponible. Primero carga un Excel en Requisito.");return window.ExcelLocalRepo;}
  function periods(){return repo().listPeriods?repo().listPeriods():repo().getSnapshot().periods||[];}
  function rawStudents(){return repo().listAllStudents?repo().listAllStudents():repo().getSnapshot().students||[];}
  function pick(row,names){for(var i=0;i<names.length;i++){var v=row[names[i]];if(text(v))return text(v);}return "";}
  function normalizeDate(v){var value=text(v);if(!value)return "";var d=value.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);if(d){var day=d[1].padStart(2,"0"),mon=d[2].padStart(2,"0"),year=d[3].length===2?"20"+d[3]:d[3];return year+"-"+mon+"-"+day;}var iso=value.match(/^(\d{4})[\/\-](\d{1,2})[\/\-](\d{1,2})/);if(iso)return iso[1]+"-"+iso[2].padStart(2,"0")+"-"+iso[3].padStart(2,"0");return value;}
  function normalizeTime(v){var value=text(v);if(!value)return "";var m=value.match(/(\d{1,2})[:hH](\d{2})/);if(m)return m[1].padStart(2,"0")+":"+m[2];return value;}
  function decorate(row){var r=Object.assign({},row||{});r._id=text(r._docId||r.docId||r.cedula||r.numeroIdentificacion||r.numeroidentificacion);r._cedula=text(r.cedula||r.numeroIdentificacion||r.numeroidentificacion);r._nombres=text(r.nombres||r.nombre||r.estudiante);r._carrera=text(r.nombrecarrera||r.nombreCarrera||r.carrera)||"SIN CARRERA";r._periodo=text(r.periodoLabel||r.periodoId)||"SIN PERÍODO";r._periodoId=text(r.periodoId);r._correo=text(r.correopersonal||r.correoPersonal||r.correoinstitucional||r.correoInstitucional);r._celular=text(r.celular||r.telefono||r.whatsapp);r._fecha=normalizeDate(pick(r,["fechaDefensa","fechadefensa","fecha","dia","día","Dia","Día"]));r._hora=normalizeTime(pick(r,["horaDefensa","horadefensa","hora","horarioDefensa","horariodefensa"]));r._aula=pick(r,["aula","Aula","salon","salón"]);r._sede=pick(r,["sede","Sede","campus"]);r._modo=pick(r,["modo","modalidad","tipoDefensa","tipodefensa"])||r._sede;r._tribunal1=pick(r,["tribunal1","tribunal 1","Tribunal 1","docente1","tutor1"]);r._tribunal2=pick(r,["tribunal2","tribunal 2","Tribunal 2","docente2","tutor2"]);r._programada=!!(r._fecha||r._hora||r._aula);return r;}
  function filtered(opts){opts=opts||{};var q=norm(opts.search),periodId=text(opts.periodId),career=text(opts.career),sede=text(opts.sede),modo=text(opts.modo);return rawStudents().map(decorate).filter(function(s){if(periodId&&s._periodoId!==periodId)return false;if(career&&s._carrera!==career)return false;if(sede&&s._sede!==sede)return false;if(modo&&norm(s._modo)!==norm(modo))return false;if(q){var hay=norm([s._cedula,s._nombres,s._carrera,s._sede,s._modo,s._aula,s._tribunal1,s._tribunal2,s._fecha,s._hora].join(" "));if(hay.indexOf(q)<0)return false;}return true;});}
  function unique(list,getter){var map={};list.forEach(function(x){var v=text(getter(x));if(v)map[v]=true;});return Object.keys(map).sort(function(a,b){return a.localeCompare(b,"es");});}
  function byCareer(list){var map={};list.forEach(function(s){var k=s._carrera;if(!map[k])map[k]={key:k,total:0,programadas:0,sinFecha:0,virtuales:0,presenciales:0};map[k].total++;if(s._programada)map[k].programadas++;else map[k].sinFecha++;if(norm(s._modo).indexOf("virtual")>=0)map[k].virtuales++;else map[k].presenciales++;});return Object.keys(map).map(function(k){return map[k];}).sort(function(a,b){return b.sinFecha-a.sinFecha||a.key.localeCompare(b.key,"es");});}
  function byTribunal(list){var map={};list.forEach(function(s){[s._tribunal1,s._tribunal2,s._aula].forEach(function(v){v=text(v);if(!v)return;if(!map[v])map[v]={key:v,total:0};map[v].total++;});});return Object.keys(map).map(function(k){return map[k];}).sort(function(a,b){return b.total-a.total||a.key.localeCompare(b.key,"es");});}
  function summary(opts){var rows=filtered(opts).sort(function(a,b){return (a._fecha||"9999").localeCompare(b._fecha||"9999")||(a._hora||"99").localeCompare(b._hora||"99")||a._nombres.localeCompare(b._nombres,"es");});var k={total:rows.length,programadas:0,sinFecha:0,virtuales:0,presenciales:0};rows.forEach(function(s){if(s._programada)k.programadas++;else k.sinFecha++;if(norm(s._modo).indexOf("virtual")>=0)k.virtuales++;else k.presenciales++;});return {rows:rows,kpis:k,carreras:byCareer(rows),tribunales:byTribunal(rows),periodList:periods(),careerList:unique(rawStudents().map(decorate),function(s){return s._carrera;}),sedeList:unique(rawStudents().map(decorate),function(s){return s._sede;}),diagnostics:{generatedAt:new Date().toISOString(),filters:opts,total:rows.length}};}
  function message(data,type,row){data=data||summary({});type=type||"general";if(type==="individual"&&row){return "Estimada/o "+(row._nombres||"estudiante")+",\n\nSe le notifica que su defensa se encuentra programada con la siguiente información:\n\nFecha: "+(row._fecha||"por confirmar")+"\nHora: "+(row._hora||"por confirmar")+"\nSede/Modalidad: "+(row._sede||row._modo||"por confirmar")+"\nAula: "+(row._aula||"por confirmar")+"\nTribunal: "+[row._tribunal1,row._tribunal2].filter(Boolean).join(" / ")+"\n\nPor favor, estar pendiente de las indicaciones institucionales.";}if(type==="pendientes"){return "Resumen de defensas sin programación:\n\nTotal sin fecha: "+(data.kpis.sinFecha||0)+".\n\nSe recomienda revisar estos casos y completar fecha, hora, aula, sede y tribunal.";}return "Resumen general de defensas:\n\nTotal estudiantes: "+(data.kpis.total||0)+".\nProgramadas: "+(data.kpis.programadas||0)+".\nSin fecha: "+(data.kpis.sinFecha||0)+".\nVirtuales: "+(data.kpis.virtuales||0)+".\nPresenciales/Matriz: "+(data.kpis.presenciales||0)+".";}
  window.DefartCore={periods:periods,summary:summary,message:message,decorate:decorate,filtered:filtered};
})(window);
